## This is test deployment for Kubernetes platforms.
## This is not intended to be used in production.
##
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: test-java
  name: test-java
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-java
  template:
    metadata:
      labels:
        app: test-java
    spec:
      containers:
      - image: bitnami/java
        name: java
