version: '2'

services:
  java:
    tty: true # Enables debugging capabilities when attached to this container.
    image: 'bitnami/java:11-rhel-7'
    command: ["tail", "-f", "/dev/null"] # To keep the container running
    ports:
      - 8080:8080
    volumes:
      - .:/app
